---@meta

-- a cs2d luals meta file

function addbind(...) end
function addhook(...) end
function ai_aim(...) end
function ai_attack(...) end
function ai_build(...) end
function ai_buy(...) end
function ai_debug(...) end
function ai_drop(...) end
function ai_findtarget(...) end
function ai_freeline(...) end
function ai_goto(...) end
function ai_iattack(...) end
function ai_move(...) end
function ai_radio(...) end
function ai_reload(...) end
function ai_respawn(...) end
function ai_rotate(...) end
function ai_say(...) end
function ai_sayteam(...) end
function ai_selectweapon(...) end
function ai_spray(...) end
function ai_use(...) end
function checksumfile(...) end
function checksumstring(...) end
function closehostage(...) end
function closeitems(...) end
function closeobjects(...) end
function closeplayers(...) end
function entity(...) end
function entitylist(...) end
function fow_in(...) end
function freehook(...) end
function freeimage(...) end
function freetimer(...) end
function funcs(...) end
function game(...) end
function hascloseplayers(...) end
function hostage(...) end
function image(...) end
function imagealpha(...) end
function imageblend(...) end
function imagecolor(...) end
function imageframe(...) end
function imagehitzone(...) end
function imageparam(...) end
function imagepos(...) end
function imagescale(...) end
function inentityzone(...) end
function item(...) end
function itemtype(...) end
function map(...) end
function menu(...) end
function msg(...) end
function msg2(...) end
function object(...) end
function objectat(...) end
function objecttype(...) end
function parse(...) end
function player(...) end
function playerammo(...) end
function playerweapons(...) end
function print(...) end
function projectile(...) end
function projectilelist(...) end
function randomentity(...) end
function randomhostage(...) end
function removeallbinds(...) end
function removebind(...) end
function reqcld(...) end
function reqhttp(...) end
function setentityaistate(...) end
function sethookstate(...) end
function stats(...) end
function steamstats(...) end
function tile(...) end
function tileproperty(...) end
function timer(...) end
function tween_alpha(...) end
function tween_animate(...) end
function tween_color(...) end
function tween_frame(...) end
function tween_move(...) end
function tween_rotate(...) end
function tween_rotateconstantly(...) end
function tween_scale(...) end
function vars(...) end
