---@meta

-- a cs2d luals meta file


---@return ...
function addbind(...) end

---@return ...
function addhook(...) end

---@return ...
function ai_aim(...) end

---@return ...
function ai_attack(...) end

---@return ...
function ai_build(...) end

---@return ...
function ai_buy(...) end

---@return ...
function ai_debug(...) end

---@return ...
function ai_drop(...) end

---@return ...
function ai_findtarget(...) end

---@return ...
function ai_freeline(...) end

---@return ...
function ai_goto(...) end

---@return ...
function ai_iattack(...) end

---@return ...
function ai_move(...) end

---@return ...
function ai_radio(...) end

---@return ...
function ai_reload(...) end

---@return ...
function ai_respawn(...) end

---@return ...
function ai_rotate(...) end

---@return ...
function ai_say(...) end

---@return ...
function ai_sayteam(...) end

---@return ...
function ai_selectweapon(...) end

---@return ...
function ai_spray(...) end

---@return ...
function ai_use(...) end

---@return ...
function checksumfile(...) end

---@return ...
function checksumstring(...) end

---@return ...
function closehostage(...) end

---@return ...
function closeitems(...) end

---@return ...
function closeobjects(...) end

---@return ...
function closeplayers(...) end

---@return ...
function entity(...) end

---@return ...
function entitylist(...) end

---@return ...
function fow_in(...) end

---@return ...
function freehook(...) end

---@return ...
function freeimage(...) end

---@return ...
function freetimer(...) end

---@return ...
function funcs(...) end

---@return ...
function game(...) end

---@return ...
function hascloseplayers(...) end

---@return ...
function hostage(...) end

---@return ...
function image(...) end

---@return ...
function imagealpha(...) end

---@return ...
function imageblend(...) end

---@return ...
function imagecolor(...) end

---@return ...
function imageframe(...) end

---@return ...
function imagehitzone(...) end

---@return ...
function imageparam(...) end

---@return ...
function imagepos(...) end

---@return ...
function imagescale(...) end

---@return ...
function inentityzone(...) end

---@return ...
function item(...) end

---@return ...
function itemtype(...) end

---@return ...
function map(...) end

---@return ...
function menu(...) end

---@return ...
function msg(...) end

---@return ...
function msg2(...) end

---@return ...
function object(...) end

---@return ...
function objectat(...) end

---@return ...
function objecttype(...) end

---@return ...
function parse(...) end

---@return ...
function player(...) end

---@return ...
function playerammo(...) end

---@return ...
function playerweapons(...) end

---@return ...
function print(...) end

---@return ...
function projectile(...) end

---@return ...
function projectilelist(...) end

---@return ...
function randomentity(...) end

---@return ...
function randomhostage(...) end

---@return ...
function removeallbinds(...) end

---@return ...
function removebind(...) end

---@return ...
function reqcld(...) end

---@return ...
function reqhttp(...) end

---@return ...
function setentityaistate(...) end

---@return ...
function sethookstate(...) end

---@return ...
function stats(...) end

---@return ...
function steamstats(...) end

---@return ...
function tile(...) end

---@return ...
function tileproperty(...) end

---@return ...
function timer(...) end

---@return ...
function tween_alpha(...) end

---@return ...
function tween_animate(...) end

---@return ...
function tween_color(...) end

---@return ...
function tween_frame(...) end

---@return ...
function tween_move(...) end

---@return ...
function tween_rotate(...) end

---@return ...
function tween_rotateconstantly(...) end

---@return ...
function tween_scale(...) end

---@return ...
function vars(...) end
