name: CI

on:
  push:
    branches:
      - master
    paths:
      - "lua/**"
  pull_request:
    paths:
      - "lua/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - name: Setup Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      
      - name: Install build deps
        run: |
          luarocks install luacheck

      - name: Get added, modified and changed files
        id: amc-files
        uses: tj-actions/changed-files@v35
        with:
          files: lua/**/*.lua

      - name: Lint
        run: |
          changed_files=""
          for p in ${{ steps.amc-files.outputs.all_changed_and_modified_files }}; do
            changed_files="$p"$'\n'
          done

          # verify changed directories
          echo "${changed_files:-No changed directories}"
          [[ -n "$changed_files" ]] && echo "changed_files=$changed_files" >> $GITHUB_ENV

          for d in $changed_dirs; do
            luacheck "$d"
          done

      - name: Build
        run: |
          if [[ -n "$changed_files" ]]; then
            for f in $changed_files; do
              script_name="$(sed -E 's#lua/([a-zA-Z0-9]+)/#\1#' <<< "$f")"
              scripts/make-script.sh "$script_name"
            done
          else echo "Skipped."; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: amalg-out
          path: |
            out/*
            !out/.PLACEHOLDER
