name: CI

on:
  push:
    branches:
      - main
    paths:
      - "lua/**"
  pull_request:
    paths:
      - "lua/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - name: Setup Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      
      - name: Install build deps
        run: |
          luarocks install luacheck

      - name: Get added, modified and changed files
        id: amc-files
        uses: tj-actions/changed-files@v35
        with:
          files: lua/**/*.lua

      - name: Lint
        run: |
          for p in ${{ steps.amc-files.outputs.all_changed_and_modified_files }}; do
            dir="$(dirname "$p")"
            if [[ -z "$old_dir" || -n ${blacklists[$p]} && ! "$dir" = "$old_dir" ]]; then
              echo "$dir" > $HOME/list-dirs.txt
            fi
            old_dir="$dir"
          done

          # verify changed directories
          echo "========= Changed directories ========="
          cat "$HOME/list-dirs.txt" || echo "No changed directories"

          for d in $(cat "$HOME/list-dirs.txt"); do
            luacheck "$d"
          done

      - name: Build
        run: |
          for d in $(cat "$HOME/list-dirs.txt"); do
            script_name="${d##*/}"
            scripts/make-script.sh "$script_name"
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: amalg-out
          path: |
            out/*
            !out/.PLACEHOLDER
